language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -e .
script: 
  - pip install pytest pytest-cov #install test framework
  - python -m pytest flood_tool --cov=flood_tool
  - python -m score -v #also check scoring runs
